### ISSUE TITLE
Removing the key from the KV when gracefully leaving the akka cluster

### ISSUE THREAD

**Issue by raboof** [hseeberger/constructr#46] opened 2015-12-15 13:44 UTC
When an akka cluster node gracefully leaves the cluster, wouldn't it make sense to remove it from the KV store (instead of waiting until it times out)?

**Comment by hseeberger** [comment] 2015-12-15 15:32
Please browse the existing issues ;-)
Duplicate of #24.

**Closed** 2015-12-15 15:32 UTC
Labels: duplicate

**Comment by raboof** [comment] 2015-12-15 15:37
Whoops missed it, sorry
